version: "3"

services:
  app:
    runtime: ${CONTAINER_RUNTIME}

    image: ${CONTAINER_USER}-noetic:see-spot-run

    hostname: ${CONTAINER_USER}-noetic:see-spot-run@${CONTAINER_HOST}

    build:
      context: ..
      dockerfile: see-spot-run/Dockerfile
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_USER: ${CONTAINER_USER}

    environment:
      # X session
      - DISPLAY=${DISPLAY}
      # Docker-to-host audio forwarding
      - PULSE_SERVER=unix:/run/user/${CONTAINER_UID}/pulse/native

    volumes:
      - /home/${CONTAINER_USER}:/home/${CONTAINER_USER}
      - /usr/local/cuda:/usr/local/cuda
      - /opt/libtorch:/opt/libtorch
      - ../dockerrc:/dockerrc
      # X session
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Docker-to-host audio forwarding
      - /etc/alsa:/etc/alsa
      - /usr/share/alsa:/usr/share/alsa
      - /run/user/${CONTAINER_UID}/pulse/native:/run/user/${CONTAINER_UID}/pulse/native

    # Using the host system's IPC namespace fixes UI glitches in rviz.
    #
    # https://stackoverflow.com/a/68490352
    ipc: host

    network_mode: host

    # Allows the container to see all of the host's devices. Somewhat less
    # secure than specifying each device individually, but makes it easier to
    # deal with additional connections and changes to the USB ports.
    privileged: true
