version: "3"

services:
  app:
    extends:
      file: ../compose.shared.yaml
      service: app

    group_add:
      - "dialout"

    environment:
      # Docker-to-host audio forwarding
      - PULSE_SERVER=unix:/run/user/${CONTAINER_UID}/pulse/native

    volumes:
      # Docker-to-host audio forwarding
      - /etc/alsa:/etc/alsa:ro
      - /usr/share/alsa:/usr/share/alsa:ro
      - /run/user/${CONTAINER_UID}/pulse/native:/run/user/${CONTAINER_UID}/pulse/native:ro

    # Allows the container to see all of the host's devices. Somewhat less
    # secure than specifying each device individually, but makes it easier to
    # deal with additional connections and changes to the USB ports.
    privileged: true
